<a href="https://colab.research.google.com/github/lohitkumar2612/NLP-Lab/blob/main/NLP_LAB_EXPERIMENT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Program to implement the **Minimum Edit Distance** algorithm using Python.

In [1]:
#Minimum edit distance

import numpy as np # Numpy library is used to access multi dimensional arrays and matrices

def minimum_edit_Distance(X, Y):
    Xlen, Ylen = len(X), len(Y)
    #For adding zeroes in first row and first colunm
    table = np.zeros( (Xlen+1, Ylen+1), dtype=int)

    for i in range(1, Xlen+1):
        table[i, 0] = table[i-1, 0] + 1  # del cost - 1
    
    for j in range(1, Ylen+1):
        table[0, j] = table[0, j-1] + 1  #ins-cose - 1
    
    # Recurrence relation
    for i in range(1, Xlen+1):
        for j in range(1, Ylen+1):
          # It returns the min value 
            table[i, j] = min(
                table[i-1, j] + 1,  #top value
                table[i, j-1] + 1,  #left value
                table[i-1, j-1] if (X[i-1]==Y[j-1]) else table[i-1, j-1]+2    #diagonal value
            )
    print(table)
    return table[Xlen, Ylen] # Last value of the matrix,it gives the minimum steps to reach from source to target


source = "sunday"
target = "saturday"
print(f'Distance between {source} and {target} is {minimum_edit_Distance(source, target)}')

[[0 1 2 3 4 5 6 7 8]
 [1 0 1 2 3 4 5 6 7]
 [2 1 2 3 2 3 4 5 6]
 [3 2 3 4 3 4 5 6 7]
 [4 3 4 5 4 5 4 5 6]
 [5 4 3 4 5 6 5 4 5]
 [6 5 4 5 6 7 6 5 4]]
Distance between sunday and saturday is 4
